version: '3.7'
services:
  # esos-server:
  #   image: esos-server
  #   environment:
  #     host: http://localhost
  #     port: 8080
  #     MONGODB_URI: 'mongodb://esos-mongo:27017/esos-mongo'
  #     COOKIE_SECRET: '0e9eadd8-0525-4a80-b55b-590182f9b69f'
  #     JWT_SECRET: '675a6315-bef2-439b-a182-cbe63b8aac3b'
  #     TWILIO_ACCOUNT_SID: "ACaa9d1226096e80c7ed5256edcc046cc0"
  #     TWILIO_AUTH_TOKEN: "36eb4f7092607adc01f382995d22b640"
  #     TWILIO_SERVICE_SID: "VA7afe259265faf97cbc7f1d27a03d093d"
  #     HASH_SECRET: "DDB651DA4722588F9A243EA7845BBCB0"
  #     INIT_VECTOR: "D39C92D9427A3F54"
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - esos-mongo
  esos-mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - esos-mongodb-volume:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.runCommand('ping')" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  esos-mongodb-volume:
